"""initial migration

Revision ID: 20230504141940
Revises: 
Create Date: 2023-05-04 14:19:41.285165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20230504141940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('character_name_idx', 'character', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('default_model', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('user_created_time_idx', 'user', ['created_time'], unique=False)
    op.create_index('user_email_idx', 'user', ['email'], unique=True)
    op.create_index('user_last_login_time', 'user', ['last_login_time'], unique=False)
    op.create_index('user_username_idx', 'user', ['username'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('conversation_character_id_idx', 'conversation', ['character_id'], unique=False)
    op.create_index('conversation_created_time_idx', 'conversation', ['created_time'], unique=False)
    op.create_index('conversation_hidden_idx', 'conversation', ['hidden'], unique=False)
    op.create_index('conversation_updated_time_idx', 'conversation', ['updated_time'], unique=False)
    op.create_index('conversation_user_id_idx', 'conversation', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('message_conversation_id_idx', 'message', ['conversation_id'], unique=False)
    op.create_index('message_created_time_idx', 'message', ['created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('message_created_time_idx', table_name='message')
    op.drop_index('message_conversation_id_idx', table_name='message')
    op.drop_table('message')
    op.drop_index('conversation_user_id_idx', table_name='conversation')
    op.drop_index('conversation_updated_time_idx', table_name='conversation')
    op.drop_index('conversation_hidden_idx', table_name='conversation')
    op.drop_index('conversation_created_time_idx', table_name='conversation')
    op.drop_index('conversation_character_id_idx', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('user_username_idx', table_name='user')
    op.drop_index('user_last_login_time', table_name='user')
    op.drop_index('user_email_idx', table_name='user')
    op.drop_index('user_created_time_idx', table_name='user')
    op.drop_table('user')
    op.drop_index('character_name_idx', table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
