"""add character schema

Revision ID: bb4b8f851520
Revises: 001
Create Date: 2023-05-04 09:37:22.994514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4b8f851520'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('character_name_idx', 'character', ['name'], unique=False)
    op.add_column('conversation', sa.Column('character_id', sa.Integer(), nullable=False))
    op.create_index('conversation_character_id_idx', 'conversation', ['character_id'], unique=False)
    op.create_foreign_key(None, 'conversation', 'character', ['character_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_index('conversation_character_id_idx', table_name='conversation')
    op.drop_column('conversation', 'character_id')
    op.drop_index('character_name_idx', table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
