"""initial setup

Revision ID: 20230511215942
Revises: 
Create Date: 2023-05-11 21:59:43.834896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20230511215942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('voice', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('voice')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index('character_name_idx', ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('default_model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('user_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('user_email_idx', ['email'], unique=True)
        batch_op.create_index('user_last_login_at', ['last_login_at'], unique=False)
        batch_op.create_index('user_username_idx', ['username'], unique=True)

    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index('conversation_character_id_idx', ['character_id'], unique=False)
        batch_op.create_index('conversation_created_time_idx', ['created_time'], unique=False)
        batch_op.create_index('conversation_hidden_idx', ['hidden'], unique=False)
        batch_op.create_index('conversation_updated_time_idx', ['updated_time'], unique=False)
        batch_op.create_index('conversation_user_id_idx', ['user_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('message_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_created_time_idx', ['created_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('message_created_time_idx')
        batch_op.drop_index('message_conversation_id_idx')

    op.drop_table('message')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('conversation_user_id_idx')
        batch_op.drop_index('conversation_updated_time_idx')
        batch_op.drop_index('conversation_hidden_idx')
        batch_op.drop_index('conversation_created_time_idx')
        batch_op.drop_index('conversation_character_id_idx')

    op.drop_table('conversation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('user_username_idx')
        batch_op.drop_index('user_last_login_at')
        batch_op.drop_index('user_email_idx')
        batch_op.drop_index('user_created_at_idx')

    op.drop_table('user')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index('character_name_idx')

    op.drop_table('character')
    # ### end Alembic commands ###
